---
name: tests
on:
  push:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.14'
          - '3.13'
          - '3.12'
          - '3.11'
          - '3.10'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ matrix.python }}
          enable-cache: true
      - run: uv run --locked pytest -n auto
